"""add rate_limit_rpm to gateway_keys

Revision ID: b84eb3d51464
Revises: e7e89709f21c
Create Date: 2026-02-27 23:08:36.079976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84eb3d51464'
down_revision: Union[str, Sequence[str], None] = 'e7e89709f21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_keys', sa.Column('rate_limit_rpm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gateway_keys', 'rate_limit_rpm')
    # ### end Alembic commands ###
